# Use Node.js image as the base image
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy the entire project into the container
COPY . .

# Install dependencies
RUN npm install

# Build the react app
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Run the react app when the container starts
CMD ["npm", "start"]
